name: Flutter Web Build

on:
  push:
    branches:
      - feature/pwa-tv-foundation
  workflow_dispatch:

jobs:
  web-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Flutter version
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.47.2'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --dart-define-from-file=.mock.json
